name: "Deployment Pipeline"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: "Install Dependencies"
        run: yarn
      - name: "Lint"
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: "Install Dependencies"
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib
  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: "Install Dependencies"
        run: yarn
      - uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib
      - name: Test
        run: yarn test
  publish_to_github_packages:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: "Install Dependencies"
        run: npm install
      - name: "build"
        run: npm run build
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGE_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
